Update streamly to the latest commit on master
psibi/streamly-bytestring pull request #12
Opened 2021-03-23 13:30 UTC by adithyaov

Preparing streamly-bytestring for a new release compatable with streamly-0.8.0

2021-04-09 11:15 UTC, harendra-kumar commented
Why are the builds failing? Can we fix them and commit this PR?

2021-04-09 11:20 UTC, harendra-kumar requested changes

2021-04-09 11:20 UTC, harendra-kumar commented on src/Streamly/External/ByteString.hs
> +import Streamly.Internal.Data.Fold (Fold)
Can we import Streamly.Data.Fold instead?

2021-04-09 11:20 UTC, harendra-kumar commented on src/Streamly/External/ByteString.hs
> +import Streamly.Internal.Data.Unfold.Type (Unfold)
Can we import this from Streamly.Data.Unfold?

2021-04-09 11:20 UTC, harendra-kumar commented on src/Streamly/External/ByteString.hs
> +import qualified Streamly.Internal.Data.Array.Foreign as Array
Can we import Streamly.Data.Array.Foreign instead? And just import selected APIs from Internal if any.

2021-04-09 11:20 UTC, harendra-kumar commented on src/Streamly/External/ByteString/Lazy.hs
> +import qualified Streamly.Internal.Data.Unfold as Unfold
Minimize Internal imports as much as possible.

2021-06-28 19:18 UTC, harendra-kumar commented
This can be closed in favor of #13 .

2021-06-28 20:30 UTC, adithyaov commented
Closing in favor of #13

2021-06-28 20:30 UTC, closed without merging