Implement fromChunksIO and update docs
psibi/streamly-bytestring pull request #8
Opened 2020-01-31 11:20 UTC by adithyaov

Thanks to @hasufell for the notification of the issue :-)

Refer #7

2020-01-31 11:29 UTC, adithyaov commented
@hasufell It would be great if you could find time to review this PR :-)

2020-01-31 12:10 UTC, hasufell commented on src/Streamly/External/ByteString/Lazy.hs
> +-- monad.
I think we should explicitly mention that all IO here will be evaluated lazily.

2020-02-04 12:01 UTC, harendra-kumar requested changes

2020-02-04 12:01 UTC, harendra-kumar commented on README.md
> +
If you are writing code from scratch, please use `Streamly.Memory.Array` which is a generalization of `ByteString` and better integrated with streamly. This library is to enable interoperation of streamly with existing code that uses `ByteString`.  

The package provides APIs to interconvert between strict Bytestring and streamly `Array Word8`  and between lazy `Bytestring` and stream of `Array Word8` . The interconversion has no overhead as the underlying representation of ByteString and Array are the same, we just need to rewrap the data in a different type.

2020-02-04 12:01 UTC, harendra-kumar commented on README.md
>  ## Description
This section can be removed. This is mostly reference documentation which should be in the haddock docs.

2020-02-04 12:01 UTC, harendra-kumar commented on src/Streamly/External/ByteString/Lazy.hs
> +-- here should be lazy in nature.
We can rewrite line 64-70 like this:

IMPORTANT NOTE: This function is lazy only for lazy monads (e.g. Identity). For strict monads (e.g. IO) it consumes the entire input before generating the output. For IO monad please use `fromChunksIO` instead.

For strict monads like IO you could create a `newtype` wrapper to make the monad bind operation lazy and lift the stream to that type using `hoist`, then you can use this function to generate the bytestring lazily. For example you can wrap the IO type to make the bind lazy like this:

2020-02-04 12:01 UTC, harendra-kumar commented on src/Streamly/External/ByteString/Lazy.hs
> +-- is in the /IO/ monad.
The text from "Although" onwards can be removed.

2020-02-07 13:52 UTC, merged

2020-02-07 13:53 UTC, adithyaov commented
@psibi Can you please make another release when you find the time. Thanks!